apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-controller
  template:
    metadata:
      labels:
        app: configuration-controller
        type: app
    spec:
      containers:
      - name: configuration-controller
        image: configuration-controller
        volumeMounts:
        - name: certificates
          mountPath: /backend/configuration_controller/certs
          readOnly: true
      volumes:
      - name: certificates
        projected:
          sources:
          - secret:
              name: certificate-certs
          - secret:
              name: certificate-keys
