apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-sas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-sas
      type: tests
  template:
    metadata:
      labels:
        app: fake-sas
        type: tests
    spec:
      containers:
      - name: fake-sas
        image: melvin10001/fakesas:0.1.0
        volumeMounts:
        - name: certificates
          mountPath: /opt/server/certs
          readOnly: true
      volumes:
      - name: certificates
        projected:
          sources:
          - secret:
              name: certificate-certs
          - secret:
              name: certificate-keys
