# Setting coverage targets per flag
coverage:
  status:
    project:
      default:
        target: 0% #overall project/ repo coverage
      active_mode_controller:
        target: 75%
        flags:
          - active-mode-controller
      configuration_controller:
        target: 0%
       flags:
          - configuration-controller
      protocol_controller:
        target: 0%
        flags:
          - protocol-controller
      radio_controller:
        target: 0%
        flags:
          - radio-controller
