apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: domain-proxy
build:
  artifacts:
    - image: configuration-controller
      context: configuration_controller
    - image: protocol-controller
      context: protocol_controller
deploy:
  kubectl:
    manifests:
      - ./tools/deployment/configuration_controller_*.yml
      - ./tools/deployment/sas_protocol_controller_*.yml

profiles:
- name: ci
  build:
    local:
      push: false
      concurrency: 0
    artifacts:
    - image: configuration-controller
      context: configuration_controller
    - image: configuration-controller-tests
      context: configuration_controller
      docker:
        buildArgs:
          ENV: 'tests'
    - image: protocol-controller
      context: protocol_controller
    - image: protocol-controller-tests
      context: protocol_controller
      docker:
        buildArgs:
          ENV: 'tests'
  deploy:
    kubectl:
      manifests:
        - ./tools/deployment/tests/configuration_controller_*.yml
  #      - ./tools/deployment/tests/sas_protocol_controller_*.yml
  activation:
  - env: CI=true
