apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: domain-proxy
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: protocol-controller
      context: .
      docker:
        dockerfile: protocol_controller/Dockerfile

    - image: configuration-controller
      context: configuration_controller

    - image: radio-controller
      context: .
      docker:
        dockerfile: radio_controller/Dockerfile

deploy:
  helm:
    flags:
      install:
        - "--debug"
    releases:
      - name: domain-proxy
        chartPath: ./charts/domain-proxy
        valuesFiles:
          - ./charts/domain-proxy/values.yaml
        namespace: default
        version: "0.1.0"
        #wait: true
        setValues:
          protocol_controller:
            tlsConfig:
              paths:
                cert: "certificates/protocol_controller/domain_proxy_bundle.cert"
                key:  "certificates/protocol_controller/domain_proxy_server.key"
                ca:  "certificates/protocol_controller/ca.cert"
        artifactOverrides:
          configuration_controller:
            image: configuration-controller
          protocol_controller:
            image: protocol-controller
          radio_controller:
            image: radio-controller

profiles:
  - name: ci
    patches:
      - op: remove
        path: /deploy/helm
    build:
      tagPolicy:
        sha256: {}
      local:
        push: false
        concurrency: 0
      artifacts:
        - image: configuration-controller-tests
          context: configuration_controller
          docker:
            buildArgs:
              ENV: 'tests'

        - image: protocol-controller-tests
          context: .
          docker:
            dockerfile: protocol_controller/Dockerfile
            buildArgs:
              ENV: 'tests'
    deploy:
      kubectl:
        manifests:
          - ./tools/deployment/tests/configuration_controller_*.yml
          #- ./tools/deployment/tests/sas_protocol_controller_*.yml
    activation:
      - env: CI=true

