apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: domain-proxy
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: protocol-controller
      context: protocol_controller
    - image: configuration-controller
      context: configuration_controller
    - image: configuration-controller-tests
      context: configuration_controller
      docker:
        buildArgs:
          ENV: 'tests'
deploy:
  helm:
    releases:
      - name: domain-proxy
        chartPath: ./charts/domain-proxy
        valuesFiles:
          - ./charts/domain-proxy/values.yaml
        namespace: default
        version: "0.1.0"
        wait: true
        artifactOverrides:
          configuration_controller:
            image: configuration-controller
          protocol_controller:
            image: protocol-controller

profiles:
  - name: ci
    patches:
      - op: remove
        path: /deploy/helm
    build:
      local:
        push: false
        concurrency: 0
      artifacts:
        - image: configuration-controller-tests
          context: configuration_controller
          docker:
            buildArgs:
              ENV: 'tests'
        - image: protocol-controller-tests
          context: protocol_controller
          docker:
            buildArgs:
              ENV: 'tests'
    deploy:
      kubectl:
        manifests:
          - ./tools/deployment/tests/configuration_controller_*.yml
    activation:
      - env: CI=true

