apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: domain-proxy
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
    concurrency: 0
  artifacts:
    - image: protocol-controller
      context: .
      docker:
        dockerfile: protocol_controller/Dockerfile
    - image: configuration-controller
      context: .
      docker:
        dockerfile: configuration_controller/Dockerfile
    - image: radio-controller
      context: .
      docker:
        dockerfile: radio_controller/Dockerfile
    - image: db-service
      context: .
      docker:
        dockerfile: db_service/Dockerfile
deploy:
  helm:
    flags:
      install:
        - "--debug"
    releases:
      - name: domain-proxy
        chartPath: ./charts/domain-proxy
        valuesFiles:
          - ./charts/domain-proxy/examples/minikube_values.yml
        namespace: default
        version: "0.1.0"
        #wait: true
        artifactOverrides:
          configuration_controller:
            image: configuration-controller
          protocol_controller:
            image: protocol-controller
          radio_controller:
            image: radio-controller
          db_service:
            image: db-service
        imageStrategy:
          helm: {}
profiles:
  - name: integration-tests
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: protocol-controller-tests
          context: .
          docker:
            dockerfile: protocol_controller/Dockerfile
            buildArgs:
              ENV: 'tests'
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          protocol_controller:
            enabled: false
          radio_controller:
            extraEnv:
              SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:password@db:5432/dp_test"
          configuration_controller:
            extraEnv:
              SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:password@db:5432/dp_test"
      - op: add
        path: /deploy/kubectl
        value:
          flags:
            apply:
              - "--force=true"
          manifests:
           - "./tools/deployment/tests/protocol_controller_*.yml"
    activation:
      - env: CI=true

  - name: nginx-ingress
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/0
        value: ./charts/domain-proxy/examples/minikube_values_nginx.yml
