apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: configuration-controller
build:
  artifacts:
    - image: configuration-controller
      context: configuration_controller
deploy:
  kubectl:
    manifests:
      - ./tools/deployment/configuration_controller_*.yaml

profiles:
- name: ci
  build:
    local:
      push: false
  activation:
  - env: CI=true
