apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: configuration-controller
build:
  artifacts:
    - image: configuration-controller
      context: configuration_controller
deploy:
  kubectl:
    manifests:
      - https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml
      - ./tools/deployment/*.yaml

