apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: domain-proxy
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: protocol-controller
      context: .
      docker:
        dockerfile: protocol_controller/Dockerfile

    - image: configuration-controller
      context: configuration_controller

    - image: radio-controller
      context: .
      docker:
        dockerfile: radio_controller/Dockerfile

deploy:
  helm:
    flags:
      install:
        - "--debug"
    releases:
      - name: domain-proxy
        chartPath: ./charts/domain-proxy
        valuesFiles:
          - ./charts/domain-proxy/values.yaml
        namespace: default
        version: "0.1.0"
        #wait: true
        artifactOverrides:
          configuration_controller:
            image: configuration-controller
          protocol_controller:
            image: protocol-controller
          radio_controller:
            image: radio-controller
        setValues:
          protocol_controller:
            tlsConfig:
              paths:
                cert: "certificates/protocol_controller/domain_proxy_bundle.cert"
                key:  "certificates/protocol_controller/domain_proxy_server.key"
                ca:  "certificates/protocol_controller/ca.cert"

profiles:
  - name: protocol-controller-integration-tests
    build:
      tagPolicy:
        sha256: {}
      local:
        push: false
        concurrency: 0

      artifacts:
        - image: protocol-controller-tests
          context: .
          docker:
            dockerfile: protocol_controller/Dockerfile
            buildArgs:
              ENV: 'tests'

        - image: configuration-controller
          context: configuration_controller

        - image: radio-controller
          context: .
          docker:
            dockerfile: radio_controller/Dockerfile
    deploy:
      helm: 
        flags:
          install:
            - "--debug"
        releases:
          - name: domain-proxy
            chartPath: ./charts/domain-proxy
            valuesFiles:
              - ./charts/domain-proxy/values.yaml
            namespace: default
            version: "0.1.0"
            wait: true
            artifactOverrides:
              configuration_controller:
                image: configuration-controller
              radio_controller:
                image: radio-controller
            setValues:
              protocol_controller:
                enabled: false
      kubectl:
        manifests:
          - ./tools/deployment/tests/sas_protocol_controller_*.yml
    activation:
      - env: SERVICE=PC

  - name: configuration-controller-integration-tests
    build:
      tagPolicy:
        sha256: {}
      local:
        push: false
        concurrency: 0
      artifacts:
        - image: configuration-controller-tests
          context: configuration_controller
          docker:
            buildArgs:
              ENV: 'tests'

        - image: protocol-controller
          context: .
          docker:
            dockerfile: protocol_controller/Dockerfile

        - image: radio-controller
          context: .
          docker:
            dockerfile: radio_controller/Dockerfile

    deploy:
      helm: 
        flags:
          install:
            - "--debug"
        releases:
          - name: domain-proxy
            chartPath: ./charts/domain-proxy
            valuesFiles:
              - ./charts/domain-proxy/values.yaml
            namespace: default
            version: "0.1.0"
            wait: true
            artifactOverrides:
              protocol_controller:
                image: protocol-controller
              radio_controller:
                image: radio-controller
            setValues:
              configuration_controller:
                enabled: false
      kubectl:
        manifests:
          - ./tools/deployment/tests/configuration_controller_*.yml
    activation:
      - env: SERVICE=CC
