name: Active mode controller unit tests

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "active_mode_controller/**"
      - ".github/workflows/active-mode-controller.yml"
  push:
    branches:
      - "!master"
    paths:
      - "active_mode_controller/**"
      - ".github/workflows/active-mode-controller.yml"

jobs:
  active_mode_controller_unit_tests:
    name: "Active mode controller unit tests"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: active_mode_controller

    strategy:
      matrix:
        go-version:
          - 1.16

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Go linter
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Run Go tests
      - run: |
          go test ./... -v -race -coverprofile=coverage.txt -covermode=actomic

      #- name: Upload coverage to Codecov
      #  uses: codecov/codecov-action@v1
      #  with:
      #    flags: unittests,active-mode-controller
      #    name: codecov-active-mode-controller
      #    fail_ci_if_error: true
      #    verbose: true
