name: Helm chart smoke tests

on: 
  pull_request:
    branches:
      - 'master'
    paths:
      - "charts/**"
      - ".github/workflows/helm-chart-tests.yml"

jobs:
  helm_chart_tests:
    name: "Helm chart smoke tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Minikube
      uses: manusa/actions-setup-minikube@v2.3.1
      with:
        minikube version: 'v1.18.1'
        kubernetes version: 'v1.20.2'
        github token: ${{ secrets.GITHUB_TOKEN }}
        start args: "--memory=6954m"
        driver: "docker"

    - name: Setup Minikube
      run: |
        make _ci_init

    - name: Run helm chart smoke tests
      run: | 
        CI=false make _ci_chart_smoke_tests
