name: Integration tests

on: 
  pull_request:
    branches:
      - 'master'

jobs:
  integation_tests:
    name: "All"
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TEST_DIR: /tmp/test-results-${{ matrix.service }}
    strategy:
      fail-fast: false
      matrix:
        service:
          - protocol-controller
    steps:
    - uses: actions/checkout@v2
    - name: Install Minikube
      uses: manusa/actions-setup-minikube@v2.4.1
      with:
        minikube version: 'v1.20.0'
        kubernetes version: 'v1.20.2'
        github token: ${{ secrets.GITHUB_TOKEN }}
        start args: "--memory=6952m --addons=metrics-server" 
        driver: "docker"

    - name: Setup Minikube
      run: |
        make _ci_init

    - name: Get minikube IP and prepare directory for test results
      run: |
        minikube ip
        mkdir -p $TEST_DIR
        minikube mount $TEST_DIR:$TEST_DIR &

    - name: Run integration tests
      run: | 
        make _ci_test_${{ matrix.service }}

    - name: Upload integration test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results-${{ matrix.service }}
        path: ${{ env.TEST_DIR }}
