name: Integration tests

on: 
  pull_request:
    branches:
      - 'master'

jobs:
  configuration_controller_build_and_integation_tests:
    name: "Configuration controller integration tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Minikube
      uses: manusa/actions-setup-minikube@v2.3.1
      with:
        minikube version: 'v1.18.1'
        kubernetes version: 'v1.20.2'
        github token: ${{ secrets.GITHUB_TOKEN }}
        start args: "--memory=6954m"
        driver: "docker"

    - name: Setup Minikube
      run: |
        make _ci_init

    - name: Get minikube IP and prepare directory for test results
      run: |
        minikube ip
        mkdir -p /tmp/test-results
        minikube mount /tmp/test-results:/tmp/test-results &

    - name: Run integration tests
      run: | 
        make _ci_test

    - name: Upload integration test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: /tmp/test-results/
