name: Integration Tests Results

on:
  workflow_run:
    workflows:
      - "Integration tests"
    types:
      - completed
      - requested

jobs:
  integration-test-results:
    name: Integration test results
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: configuration_controller.yml
          path: test-results

      - name: Publish integration test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          files: test-results/**/*.xml
